'use strict';

// Raju Chinese: outlets, menu and the localities customers type.
//
// Outlets: the 7 Raju Chinese Food outlets found in public listings (Zomato,
// Justdial, magicpin, Shoutlo, Mappls; Oct 2026). Sector 15, 34, 46, Phase 3B2
// and VIP Road Zirakpur are confirmed by several sources; Khuda Lahora (PGI) and
// Peer Muchalla by fewer, and Peer Muchalla's map point is estimated. Confirm
// addresses, map pins, phone numbers and hours with each outlet before launch.
//
// Still PLACEHOLDERS: UPI IDs ("@example" is deliberately invalid
// so no test payment can reach a real account) and WhatsApp payment
// configuration names.

const outlets = [
  { slug: 'sec-15-chd', upiId: 'rc-sec-15-chd@example', waPaymentConfig: 'rc-sec-15-chd', name: 'Raju Chinese - Sector 15', city: 'Chandigarh', address: 'Booth 225, Patel Market, Sector 15-D, Chandigarh 160015', lat: 30.75266, lng: 76.77114, phone: '+917696295218', radiusKm: 20, opens: '11:00', closes: '22:00' },
  { slug: 'sec-34-chd', upiId: 'rc-sec-34-chd@example', waPaymentConfig: 'rc-sec-34-chd', name: 'Raju Chinese - Sector 34', city: 'Chandigarh', address: 'Himalaya Marg, Sector 34-C, Chandigarh', lat: 30.71998, lng: 76.76560, phone: '+919041234440', radiusKm: 20, opens: '11:00', closes: '23:00' },
  { slug: 'sec-46-chd', upiId: 'rc-sec-46-chd@example', waPaymentConfig: 'rc-sec-46-chd', name: 'Raju Chinese - Sector 46', city: 'Chandigarh', address: 'Booth 43, Sector 46-C, Chandigarh', lat: 30.70053, lng: 76.76582, phone: '+918557880159', radiusKm: 20, opens: '12:00', closes: '23:00' },
  { slug: 'phase-3b2-mohali', upiId: 'rc-phase-3b2-mohali@example', waPaymentConfig: 'rc-phase-3b2-mohali', name: 'Raju Chinese - Phase 3B2 Mohali', city: 'Mohali', address: 'Booth 15, Sector 60 (Phase 3B2), near Mohali Stadium Road, SAS Nagar', lat: 30.71221, lng: 76.71924, phone: '+917710767710', radiusKm: 20, opens: '11:00', closes: '23:00' },
  { slug: 'vip-road-zirakpur', upiId: 'rc-vip-road-zirakpur@example', waPaymentConfig: 'rc-vip-road-zirakpur', name: 'Raju Chinese - VIP Road Zirakpur', city: 'Zirakpur', address: 'Amcare Plaza, VIP Road, Zirakpur 140603', lat: 30.63884, lng: 76.81542, phone: '+919779020477', radiusKm: 20, opens: '11:00', closes: '22:00' },
  { slug: 'khuda-lahora', upiId: 'rc-khuda-lahora@example', waPaymentConfig: 'rc-khuda-lahora', name: 'Raju Chinese - Khuda Lahora (PGI)', city: 'Chandigarh', address: 'Shop 149, Khuda Lahora, near PGI, Chandigarh 160014', lat: 30.77347, lng: 76.77089, phone: '+919876767891', radiusKm: 20, opens: '11:00', closes: '23:00' },
  { slug: 'peer-muchalla', upiId: 'rc-peer-muchalla@example', waPaymentConfig: 'rc-peer-muchalla', name: 'Raju Chinese - Peer Muchalla', city: 'Zirakpur', address: 'SCO 5, near Dargah, Peer Muchalla', lat: 30.665, lng: 76.835, phone: '+919780292999', radiusKm: 20, opens: '11:00', closes: '23:00' },
];

// The real dine-in menu (Raju Chinese Food menu, Oct 2026), prices in rupees.
// Dishes sold in two portions are two items, "<dish> (Half)" and "<dish> (Full)":
// each has its own price, stock and sales figures. The web app shows them on
// one card and WhatsApp asks "Half or Full?". Categories can hold any number
// of dishes; WhatsApp pages through them 9 at a time.
const menu = [
  { category: "Momos", name: "Veg Steam Momo (Half)", price: 139, veg: true },
  { category: "Momos", name: "Veg Steam Momo (Full)", price: 199, veg: true },
  { category: "Momos", name: "Veg Fried Momo (Half)", price: 149, veg: true },
  { category: "Momos", name: "Veg Fried Momo (Full)", price: 199, veg: true },
  { category: "Momos", name: "Kurkure Veg Momo (Half)", price: 159, veg: true },
  { category: "Momos", name: "Kurkure Veg Momo (Full)", price: 249, veg: true },
  { category: "Momos", name: "Veg Chilli Momo (Half)", price: 169, veg: true },
  { category: "Momos", name: "Veg Chilli Momo (Full)", price: 269, veg: true },
  { category: "Momos", name: "Afghani Veg Momo (Half)", price: 169, veg: true },
  { category: "Momos", name: "Afghani Veg Momo (Full)", price: 269, veg: true },
  { category: "Momos", name: "Red Sauce Veg Momo (Half)", price: 179, veg: true },
  { category: "Momos", name: "Red Sauce Veg Momo (Full)", price: 269, veg: true },
  { category: "Momos", name: "Mix Sauce Veg Momo (Half)", price: 179, veg: true },
  { category: "Momos", name: "Mix Sauce Veg Momo (Full)", price: 269, veg: true },
  { category: "Momos", name: "Tandoori Sauce Veg Momo (Half)", price: 179, veg: true },
  { category: "Momos", name: "Tandoori Sauce Veg Momo (Full)", price: 269, veg: true },
  { category: "Momos", name: "Veg Korean BBQ Momo (Half)", price: 179, veg: true },
  { category: "Momos", name: "Veg Korean BBQ Momo (Full)", price: 269, veg: true },
  { category: "Momos", name: "Paneer Steam Momo (Half)", price: 149, veg: true },
  { category: "Momos", name: "Paneer Steam Momo (Full)", price: 249, veg: true },
  { category: "Momos", name: "Paneer Fried Momo (Half)", price: 159, veg: true },
  { category: "Momos", name: "Paneer Fried Momo (Full)", price: 259, veg: true },
  { category: "Momos", name: "Kurkure Paneer Momo (Half)", price: 179, veg: true },
  { category: "Momos", name: "Kurkure Paneer Momo (Full)", price: 279, veg: true },
  { category: "Momos", name: "Paneer Chilli Momo (Half)", price: 189, veg: true },
  { category: "Momos", name: "Paneer Chilli Momo (Full)", price: 289, veg: true },
  { category: "Momos", name: "Afghani Paneer Momo (Half)", price: 189, veg: true },
  { category: "Momos", name: "Afghani Paneer Momo (Full)", price: 299, veg: true },
  { category: "Momos", name: "Red Sauce Paneer Momo (Half)", price: 189, veg: true },
  { category: "Momos", name: "Red Sauce Paneer Momo (Full)", price: 299, veg: true },
  { category: "Momos", name: "Mix Sauce Paneer Momo (Half)", price: 189, veg: true },
  { category: "Momos", name: "Mix Sauce Paneer Momo (Full)", price: 319, veg: true },
  { category: "Momos", name: "Tandoori Sauce Paneer Momo (Half)", price: 199, veg: true },
  { category: "Momos", name: "Tandoori Sauce Paneer Momo (Full)", price: 299, veg: true },
  { category: "Momos", name: "Paneer Korean BBQ Momo (Half)", price: 199, veg: true },
  { category: "Momos", name: "Paneer Korean BBQ Momo (Full)", price: 299, veg: true },
  { category: "Momos", name: "Chicken Steam Momo (Half)", price: 159, veg: false },
  { category: "Momos", name: "Chicken Steam Momo (Full)", price: 249, veg: false },
  { category: "Momos", name: "Chicken Fried Momo (Half)", price: 159, veg: false },
  { category: "Momos", name: "Chicken Fried Momo (Full)", price: 259, veg: false },
  { category: "Momos", name: "Kurkure Chicken Momo (Half)", price: 179, veg: false },
  { category: "Momos", name: "Kurkure Chicken Momo (Full)", price: 279, veg: false },
  { category: "Momos", name: "Chicken Chilli Momo (Half)", price: 179, veg: false },
  { category: "Momos", name: "Chicken Chilli Momo (Full)", price: 289, veg: false },
  { category: "Momos", name: "Afghani Chicken Momo (Half)", price: 189, veg: false },
  { category: "Momos", name: "Afghani Chicken Momo (Full)", price: 299, veg: false },
  { category: "Momos", name: "Red Sauce Chicken Momo (Half)", price: 189, veg: false },
  { category: "Momos", name: "Red Sauce Chicken Momo (Full)", price: 319, veg: false },
  { category: "Momos", name: "Mix Sauce Chicken Momo (Half)", price: 189, veg: false },
  { category: "Momos", name: "Mix Sauce Chicken Momo (Full)", price: 269, veg: false },
  { category: "Momos", name: "Tandoori Sauce Chicken Momo (Half)", price: 189, veg: false },
  { category: "Momos", name: "Tandoori Sauce Chicken Momo (Full)", price: 279, veg: false },
  { category: "Momos", name: "Chicken Korean BBQ Momo (Half)", price: 199, veg: false },
  { category: "Momos", name: "Chicken Korean BBQ Momo (Full)", price: 299, veg: false },
  { category: "Noodles", name: "Veg Noodles (Half)", price: 139, veg: true },
  { category: "Noodles", name: "Veg Noodles (Full)", price: 199, veg: true },
  { category: "Noodles", name: "Paneer Noodles (Half)", price: 169, veg: true },
  { category: "Noodles", name: "Paneer Noodles (Full)", price: 239, veg: true },
  { category: "Noodles", name: "Veg Hakka Noodles (Half)", price: 149, veg: true },
  { category: "Noodles", name: "Veg Hakka Noodles (Full)", price: 229, veg: true },
  { category: "Noodles", name: "Veg Chilli Garlic Noodles (Half)", price: 179, veg: true },
  { category: "Noodles", name: "Veg Chilli Garlic Noodles (Full)", price: 269, veg: true },
  { category: "Noodles", name: "Veg Gravy Noodles (Half)", price: 159, veg: true },
  { category: "Noodles", name: "Veg Gravy Noodles (Full)", price: 229, veg: true },
  { category: "Noodles", name: "Veg Schezwan Noodles (Half)", price: 169, veg: true },
  { category: "Noodles", name: "Veg Schezwan Noodles (Full)", price: 239, veg: true },
  { category: "Noodles", name: "Veg Momo Mix Noodles (Half)", price: 189, veg: true },
  { category: "Noodles", name: "Veg Momo Mix Noodles (Full)", price: 269, veg: true },
  { category: "Noodles", name: "RCF Special Veg Noodles (Half)", price: 169, veg: true },
  { category: "Noodles", name: "RCF Special Veg Noodles (Full)", price: 259, veg: true },
  { category: "Noodles", name: "Chicken Noodles (Half)", price: 169, veg: false },
  { category: "Noodles", name: "Chicken Noodles (Full)", price: 269, veg: false },
  { category: "Noodles", name: "Chicken Hakka Noodles (Half)", price: 189, veg: false },
  { category: "Noodles", name: "Chicken Hakka Noodles (Full)", price: 279, veg: false },
  { category: "Noodles", name: "Chicken Chilli Garlic Noodles (Half)", price: 189, veg: false },
  { category: "Noodles", name: "Chicken Chilli Garlic Noodles (Full)", price: 279, veg: false },
  { category: "Noodles", name: "Chicken Schezwan Noodles (Half)", price: 199, veg: false },
  { category: "Noodles", name: "Chicken Schezwan Noodles (Full)", price: 279, veg: false },
  { category: "Noodles", name: "Chicken Gravy Noodles (Half)", price: 199, veg: false },
  { category: "Noodles", name: "Chicken Gravy Noodles (Full)", price: 289, veg: false },
  { category: "Noodles", name: "Chicken Momo Mix Noodles (Half)", price: 199, veg: false },
  { category: "Noodles", name: "Chicken Momo Mix Noodles (Full)", price: 289, veg: false },
  { category: "Noodles", name: "Egg Noodles (Half)", price: 159, veg: false },
  { category: "Noodles", name: "Egg Noodles (Full)", price: 239, veg: false },
  { category: "Noodles", name: "Egg Hakka Noodles (Half)", price: 159, veg: false },
  { category: "Noodles", name: "Egg Hakka Noodles (Full)", price: 239, veg: false },
  { category: "Noodles", name: "Egg Chilli Garlic Noodles (Half)", price: 179, veg: false },
  { category: "Noodles", name: "Egg Chilli Garlic Noodles (Full)", price: 259, veg: false },
  { category: "Noodles", name: "RCF Special Non-Veg Noodles (Half)", price: 199, veg: false },
  { category: "Noodles", name: "RCF Special Non-Veg Noodles (Full)", price: 349, veg: false },
  { category: "Fried Rice", name: "Veg Fried Rice (Half)", price: 149, veg: true },
  { category: "Fried Rice", name: "Veg Fried Rice (Full)", price: 219, veg: true },
  { category: "Fried Rice", name: "Paneer Fried Rice (Half)", price: 179, veg: true },
  { category: "Fried Rice", name: "Paneer Fried Rice (Full)", price: 249, veg: true },
  { category: "Fried Rice", name: "Veg Hakka Fried Rice (Half)", price: 169, veg: true },
  { category: "Fried Rice", name: "Veg Hakka Fried Rice (Full)", price: 259, veg: true },
  { category: "Fried Rice", name: "Veg Chilli Garlic Fried Rice (Half)", price: 169, veg: true },
  { category: "Fried Rice", name: "Veg Chilli Garlic Fried Rice (Full)", price: 239, veg: true },
  { category: "Fried Rice", name: "Veg Schezwan Fried Rice (Half)", price: 179, veg: true },
  { category: "Fried Rice", name: "Veg Schezwan Fried Rice (Full)", price: 259, veg: true },
  { category: "Fried Rice", name: "Veg Momo Mix Fried Rice (Half)", price: 179, veg: true },
  { category: "Fried Rice", name: "Veg Momo Mix Fried Rice (Full)", price: 259, veg: true },
  { category: "Fried Rice", name: "RCF Special Veg Fried Rice (Half)", price: 169, veg: true },
  { category: "Fried Rice", name: "RCF Special Veg Fried Rice (Full)", price: 259, veg: true },
  { category: "Fried Rice", name: "Egg Fried Rice (Half)", price: 169, veg: false },
  { category: "Fried Rice", name: "Egg Fried Rice (Full)", price: 239, veg: false },
  { category: "Fried Rice", name: "Chicken Fried Rice (Half)", price: 179, veg: false },
  { category: "Fried Rice", name: "Chicken Fried Rice (Full)", price: 279, veg: false },
  { category: "Fried Rice", name: "Chicken Hakka Fried Rice (Half)", price: 189, veg: false },
  { category: "Fried Rice", name: "Chicken Hakka Fried Rice (Full)", price: 299, veg: false },
  { category: "Fried Rice", name: "Chicken Chilli Garlic Fried Rice (Half)", price: 189, veg: false },
  { category: "Fried Rice", name: "Chicken Chilli Garlic Fried Rice (Full)", price: 299, veg: false },
  { category: "Fried Rice", name: "Chicken Schezwan Fried Rice (Half)", price: 199, veg: false },
  { category: "Fried Rice", name: "Chicken Schezwan Fried Rice (Full)", price: 309, veg: false },
  { category: "Fried Rice", name: "Chicken Momo Mix Fried Rice (Half)", price: 199, veg: false },
  { category: "Fried Rice", name: "Chicken Momo Mix Fried Rice (Full)", price: 299, veg: false },
  { category: "Fried Rice", name: "RCF Special Non-Veg Fried Rice (Half)", price: 199, veg: false },
  { category: "Fried Rice", name: "RCF Special Non-Veg Fried Rice (Full)", price: 349, veg: false },
  { category: "Veg Starters & Mains", name: "Veg Manchurian Dry (Half)", price: 159, veg: true },
  { category: "Veg Starters & Mains", name: "Veg Manchurian Dry (Full)", price: 259, veg: true },
  { category: "Veg Starters & Mains", name: "Veg Manchurian Gravy (Half)", price: 169, veg: true },
  { category: "Veg Starters & Mains", name: "Veg Manchurian Gravy (Full)", price: 269, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Manchurian Dry (Half)", price: 169, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Manchurian Dry (Full)", price: 259, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Manchurian Gravy (Half)", price: 179, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Manchurian Gravy (Full)", price: 269, veg: true },
  { category: "Veg Starters & Mains", name: "Paneer Manchurian Dry (Half)", price: 189, veg: true },
  { category: "Veg Starters & Mains", name: "Paneer Manchurian Dry (Full)", price: 279, veg: true },
  { category: "Veg Starters & Mains", name: "Paneer Manchurian Gravy (Half)", price: 199, veg: true },
  { category: "Veg Starters & Mains", name: "Paneer Manchurian Gravy (Full)", price: 289, veg: true },
  { category: "Veg Starters & Mains", name: "Cheese Chilli Dry (Half)", price: 189, veg: true },
  { category: "Veg Starters & Mains", name: "Cheese Chilli Dry (Full)", price: 299, veg: true },
  { category: "Veg Starters & Mains", name: "Cheese Chilli Gravy (Half)", price: 199, veg: true },
  { category: "Veg Starters & Mains", name: "Cheese Chilli Gravy (Full)", price: 309, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Chilli Dry (Half)", price: 179, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Chilli Dry (Full)", price: 259, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Chilli Gravy (Half)", price: 189, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Chilli Gravy (Full)", price: 269, veg: true },
  { category: "Veg Starters & Mains", name: "Honey Chilli Cauliflower (Half)", price: 189, veg: true },
  { category: "Veg Starters & Mains", name: "Honey Chilli Cauliflower (Full)", price: 259, veg: true },
  { category: "Veg Starters & Mains", name: "Honey Chilli Potato (Half)", price: 189, veg: true },
  { category: "Veg Starters & Mains", name: "Honey Chilli Potato (Full)", price: 259, veg: true },
  { category: "Veg Starters & Mains", name: "Chilli Potato (Half)", price: 159, veg: true },
  { category: "Veg Starters & Mains", name: "Chilli Potato (Full)", price: 249, veg: true },
  { category: "Veg Starters & Mains", name: "French Fries (Half)", price: 139, veg: true },
  { category: "Veg Starters & Mains", name: "French Fries (Full)", price: 219, veg: true },
  { category: "Veg Starters & Mains", name: "Kurkure French Fries (Half)", price: 149, veg: true },
  { category: "Veg Starters & Mains", name: "Kurkure French Fries (Full)", price: 229, veg: true },
  { category: "Veg Starters & Mains", name: "Gobi Manchurian (Dry or Gravy) (Half)", price: 189, veg: true },
  { category: "Veg Starters & Mains", name: "Gobi Manchurian (Dry or Gravy) (Full)", price: 289, veg: true },
  { category: "Veg Starters & Mains", name: "Paneer Fingers", price: 279, veg: true },
  { category: "Veg Starters & Mains", name: "Paneer Crispy Popcorn", price: 259, veg: true },
  { category: "Veg Starters & Mains", name: "Mushroom Crispy Popcorn", price: 189, veg: true },
  { category: "Chicken & Fish", name: "Chilli Chicken With Bone Dry (Half)", price: 319, veg: false },
  { category: "Chicken & Fish", name: "Chilli Chicken With Bone Dry (Full)", price: 429, veg: false },
  { category: "Chicken & Fish", name: "Chilli Chicken With Bone Gravy (Half)", price: 329, veg: false },
  { category: "Chicken & Fish", name: "Chilli Chicken With Bone Gravy (Full)", price: 439, veg: false },
  { category: "Chicken & Fish", name: "Chilli Chicken Boneless Dry (Half)", price: 319, veg: false },
  { category: "Chicken & Fish", name: "Chilli Chicken Boneless Dry (Full)", price: 429, veg: false },
  { category: "Chicken & Fish", name: "Chilli Chicken Boneless Gravy (Half)", price: 329, veg: false },
  { category: "Chicken & Fish", name: "Chilli Chicken Boneless Gravy (Full)", price: 439, veg: false },
  { category: "Chicken & Fish", name: "Chicken Manchurian Dry (Half)", price: 319, veg: false },
  { category: "Chicken & Fish", name: "Chicken Manchurian Dry (Full)", price: 419, veg: false },
  { category: "Chicken & Fish", name: "Chicken Manchurian Gravy (Half)", price: 329, veg: false },
  { category: "Chicken & Fish", name: "Chicken Manchurian Gravy (Full)", price: 409, veg: false },
  { category: "Chicken & Fish", name: "Kung Pao Chicken (Half)", price: 309, veg: false },
  { category: "Chicken & Fish", name: "Kung Pao Chicken (Full)", price: 419, veg: false },
  { category: "Chicken & Fish", name: "Saucy Schezwan Chicken (Half)", price: 319, veg: false },
  { category: "Chicken & Fish", name: "Saucy Schezwan Chicken (Full)", price: 449, veg: false },
  { category: "Chicken & Fish", name: "Honey Chilli Chicken Dry (Half)", price: 319, veg: false },
  { category: "Chicken & Fish", name: "Honey Chilli Chicken Dry (Full)", price: 429, veg: false },
  { category: "Chicken & Fish", name: "Honey Chilli Chicken Gravy (Half)", price: 329, veg: false },
  { category: "Chicken & Fish", name: "Honey Chilli Chicken Gravy (Full)", price: 439, veg: false },
  { category: "Chicken & Fish", name: "Korean BBQ Wings (6 pcs)", price: 319, veg: false },
  { category: "Chicken & Fish", name: "Chicken Wings Fry (6 pcs)", price: 319, veg: false },
  { category: "Chicken & Fish", name: "Chicken Lollipop (6 pcs)", price: 329, veg: false },
  { category: "Chicken & Fish", name: "Chicken Golden Fry (8 pcs)", price: 389, veg: false },
  { category: "Chicken & Fish", name: "Chicken Crispy Popcorn", price: 259, veg: false },
  { category: "Chicken & Fish", name: "Chicken Crispy Finger", price: 299, veg: false },
  { category: "Chicken & Fish", name: "Fish Crispy Popcorn", price: 369, veg: false },
  { category: "Chicken & Fish", name: "Fish Crispy Finger", price: 369, veg: false },
  { category: "Soups & Thukpa", name: "Veg Manchow Soup", price: 129, veg: true },
  { category: "Soups & Thukpa", name: "Veg Sweet Corn Soup", price: 129, veg: true },
  { category: "Soups & Thukpa", name: "Veg Talumein Soup", price: 129, veg: true },
  { category: "Soups & Thukpa", name: "Veg Hot & Sour Soup", price: 129, veg: true },
  { category: "Soups & Thukpa", name: "Veg Tomato Soup", price: 129, veg: true },
  { category: "Soups & Thukpa", name: "Veg Thukpa (Half)", price: 149, veg: true },
  { category: "Soups & Thukpa", name: "Veg Thukpa (Full)", price: 219, veg: true },
  { category: "Soups & Thukpa", name: "Veg Momo Mix Thukpa (Half)", price: 169, veg: true },
  { category: "Soups & Thukpa", name: "Veg Momo Mix Thukpa (Full)", price: 239, veg: true },
  { category: "Soups & Thukpa", name: "Paneer Thukpa (Half)", price: 169, veg: true },
  { category: "Soups & Thukpa", name: "Paneer Thukpa (Full)", price: 239, veg: true },
  { category: "Soups & Thukpa", name: "Paneer Momo Mix Thukpa (Half)", price: 179, veg: true },
  { category: "Soups & Thukpa", name: "Paneer Momo Mix Thukpa (Full)", price: 269, veg: true },
  { category: "Soups & Thukpa", name: "Chicken Soup", price: 149, veg: false },
  { category: "Soups & Thukpa", name: "Chicken Manchow Soup", price: 159, veg: false },
  { category: "Soups & Thukpa", name: "Chicken Sweet Corn Soup", price: 159, veg: false },
  { category: "Soups & Thukpa", name: "Chicken Talumein Soup", price: 189, veg: false },
  { category: "Soups & Thukpa", name: "Chicken Hot & Sour Soup", price: 159, veg: false },
  { category: "Soups & Thukpa", name: "Chicken Thukpa (Half)", price: 179, veg: false },
  { category: "Soups & Thukpa", name: "Chicken Thukpa (Full)", price: 249, veg: false },
  { category: "Soups & Thukpa", name: "Chicken Momo Mix Thukpa (Half)", price: 189, veg: false },
  { category: "Soups & Thukpa", name: "Chicken Momo Mix Thukpa (Full)", price: 279, veg: false },
  { category: "Pasta", name: "White Sauce Pasta (Half)", price: 169, veg: true },
  { category: "Pasta", name: "White Sauce Pasta (Full)", price: 269, veg: true },
  { category: "Pasta", name: "White Sauce Paneer Pasta (Half)", price: 189, veg: true },
  { category: "Pasta", name: "White Sauce Paneer Pasta (Full)", price: 289, veg: true },
  { category: "Pasta", name: "Red Sauce Pasta (Half)", price: 159, veg: true },
  { category: "Pasta", name: "Red Sauce Pasta (Full)", price: 259, veg: true },
  { category: "Pasta", name: "Red Sauce Paneer Pasta (Half)", price: 189, veg: true },
  { category: "Pasta", name: "Red Sauce Paneer Pasta (Full)", price: 289, veg: true },
  { category: "Pasta", name: "Mix Sauce Veg Pasta (Half)", price: 169, veg: true },
  { category: "Pasta", name: "Mix Sauce Veg Pasta (Full)", price: 269, veg: true },
  { category: "Pasta", name: "Mix Sauce Paneer Pasta (Half)", price: 189, veg: true },
  { category: "Pasta", name: "Mix Sauce Paneer Pasta (Full)", price: 279, veg: true },
  { category: "Pasta", name: "Tandoori Sauce Veg Pasta (Half)", price: 169, veg: true },
  { category: "Pasta", name: "Tandoori Sauce Veg Pasta (Full)", price: 259, veg: true },
  { category: "Pasta", name: "Tandoori Sauce Paneer Pasta (Half)", price: 189, veg: true },
  { category: "Pasta", name: "Tandoori Sauce Paneer Pasta (Full)", price: 289, veg: true },
  { category: "Pasta", name: "Red Sauce Potato (Half)", price: 169, veg: true },
  { category: "Pasta", name: "Red Sauce Potato (Full)", price: 239, veg: true },
  { category: "Pasta", name: "White Sauce Potato (Half)", price: 169, veg: true },
  { category: "Pasta", name: "White Sauce Potato (Full)", price: 239, veg: true },
  { category: "Pasta", name: "Mix Sauce Potato (Half)", price: 169, veg: true },
  { category: "Pasta", name: "Mix Sauce Potato (Full)", price: 239, veg: true },
  { category: "Pasta", name: "Tandoori Sauce Potato (Half)", price: 169, veg: true },
  { category: "Pasta", name: "Tandoori Sauce Potato (Full)", price: 239, veg: true },
  { category: "Pasta", name: "White Sauce Chicken Pasta (Half)", price: 189, veg: false },
  { category: "Pasta", name: "White Sauce Chicken Pasta (Full)", price: 289, veg: false },
  { category: "Pasta", name: "Red Sauce Chicken Pasta (Half)", price: 189, veg: false },
  { category: "Pasta", name: "Red Sauce Chicken Pasta (Full)", price: 289, veg: false },
  { category: "Pasta", name: "Mix Sauce Chicken Pasta (Half)", price: 189, veg: false },
  { category: "Pasta", name: "Mix Sauce Chicken Pasta (Full)", price: 289, veg: false },
  { category: "Pasta", name: "Tandoori Sauce Chicken Pasta (Half)", price: 189, veg: false },
  { category: "Pasta", name: "Tandoori Sauce Chicken Pasta (Full)", price: 289, veg: false },
  { category: "Chopsuey", name: "American Veg Chopsuey (Half)", price: 199, veg: true },
  { category: "Chopsuey", name: "American Veg Chopsuey (Full)", price: 279, veg: true },
  { category: "Chopsuey", name: "Chinese Veg Chopsuey (Half)", price: 199, veg: true },
  { category: "Chopsuey", name: "Chinese Veg Chopsuey (Full)", price: 279, veg: true },
  { category: "Chopsuey", name: "American Chicken Chopsuey (Half)", price: 209, veg: false },
  { category: "Chopsuey", name: "American Chicken Chopsuey (Full)", price: 289, veg: false },
  { category: "Chopsuey", name: "Chinese Chicken Chopsuey (Half)", price: 209, veg: false },
  { category: "Chopsuey", name: "Chinese Chicken Chopsuey (Full)", price: 289, veg: false },
  { category: "Rolls", name: "Veg Spring Roll (Half)", price: 129, veg: true },
  { category: "Rolls", name: "Veg Spring Roll (Full)", price: 199, veg: true },
  { category: "Rolls", name: "Kurkure Veg Spring Roll (Half)", price: 149, veg: true },
  { category: "Rolls", name: "Kurkure Veg Spring Roll (Full)", price: 249, veg: true },
  { category: "Rolls", name: "Chicken Spring Roll (Half)", price: 149, veg: false },
  { category: "Rolls", name: "Chicken Spring Roll (Full)", price: 249, veg: false },
  { category: "Rolls", name: "Kurkure Chicken Spring Roll (Half)", price: 169, veg: false },
  { category: "Rolls", name: "Kurkure Chicken Spring Roll (Full)", price: 269, veg: false },
  { category: "Platters", name: "Raju Special Veg Platter", description: "Veg fried rice, veg noodles, veg manchurian, chilli paneer and 2 veg steam momos", price: 299, veg: true },
  { category: "Platters", name: "Raju Special Non-Veg Platter", description: "Chicken fried rice, chicken noodles, chilli chicken and 2 chicken momos", price: 399, veg: false },
];

// Approximate locality centroids: for picking an area in the web app and for
// placing typed WhatsApp addresses (src/geocode.js). Add more areas freely.
const localities = [
  ['Sector 8', 'Chandigarh', 30.7410, 76.8010], ['Sector 9', 'Chandigarh', 30.7480, 76.7930],
  ['Sector 15', 'Chandigarh', 30.7520, 76.7680], ['Sector 17', 'Chandigarh', 30.7410, 76.7790],
  ['Sector 22', 'Chandigarh', 30.7330, 76.7720], ['Sector 26', 'Chandigarh', 30.7300, 76.8070],
  ['Sector 32', 'Chandigarh', 30.7150, 76.7780], ['Sector 35', 'Chandigarh', 30.7225, 76.7570],
  ['Sector 43', 'Chandigarh', 30.7180, 76.7400], ['Sector 44', 'Chandigarh', 30.7080, 76.7550],
  ['Industrial Area Phase 1', 'Chandigarh', 30.7050, 76.8000], ['Manimajra', 'Chandigarh', 30.7290, 76.8380],
  ['Phase 3B2', 'Mohali', 30.7230, 76.7120], ['Phase 5', 'Mohali', 30.7140, 76.7200],
  ['Phase 7', 'Mohali', 30.7085, 76.7195], ['Phase 10', 'Mohali', 30.6930, 76.7310],
  ['Sector 70', 'Mohali', 30.6990, 76.7140], ['Sector 82 (IT City)', 'Mohali', 30.6680, 76.7180],
  ['Kharar', 'Kharar', 30.7460, 76.6450], ['Landran', 'Kharar', 30.7020, 76.6630],
  ['Zirakpur VIP Road', 'Zirakpur', 30.6420, 76.8170], ['Dhakoli', 'Zirakpur', 30.6560, 76.8420],
  ['Sector 5', 'Panchkula', 30.6940, 76.8600], ['Sector 11', 'Panchkula', 30.6960, 76.8480],
  ['Sector 20', 'Panchkula', 30.6710, 76.8410], ['Sector 26', 'Panchkula', 30.6870, 76.8800],
  ['Mansa Devi', 'Panchkula', 30.7310, 76.8610], ['Chandimandir', 'Panchkula', 30.7220, 76.8850],
  ['Peer Muchalla', 'Zirakpur', 30.6720, 76.8450], ['Bhabat', 'Zirakpur', 30.6400, 76.8250],
  ['Aerocity', 'Mohali', 30.6630, 76.7330], ['Sohana', 'Mohali', 30.6830, 76.7000], ['TDI City', 'Mohali', 30.6480, 76.6900],
  ['Sunny Enclave', 'Kharar', 30.7350, 76.6600], ['New Chandigarh', 'Mullanpur', 30.7870, 76.6950],
  ['PGI', 'Chandigarh', 30.7650, 76.7760], ['IT Park', 'Chandigarh', 30.7270, 76.8450],
  ['Pinjore', 'Pinjore', 30.7970, 76.9170], ['Dera Bassi', 'Dera Bassi', 30.5880, 76.8430],
  ['Kurali', 'Kurali', 30.8360, 76.5740], ['Banur', 'Banur', 30.5560, 76.7160],
].map(([name, city, lat, lng]) => ({ name, city, lat, lng }));

module.exports = { outlets, menu, localities };
